from .background_erase_network import (
    BackgroundEraseNetwork,
    NODE_CLASS_MAPPINGS as BACKGROUND_ERASE_NETWORK_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BACKGROUND_ERASE_NETWORK_DISPLAY_MAPPINGS
)

# Combined NODE_CLASS_MAPPINGS dictionary
NODE_CLASS_MAPPINGS = {
    **BACKGROUND_ERASE_NETWORK_MAPPINGS

}

# Combined NODE_DISPLAY_NAME_MAPPINGS dictionary
NODE_DISPLAY_NAME_MAPPINGS = {
    **BACKGROUND_ERASE_NETWORK_DISPLAY_MAPPINGS
}
